### ISSUE TITLE
Setup subdomain (i.e. aktivitet.team13.se) and use for main and test sites

### ISSUE THREAD

**Issue by marcus-sonestedt** [marcusl/t13activityweb#7]
The users should see a familiar domain name, not @marcusl 's account name and the webhost provider.

**TODO**

- [ ] Create subdomain redirecting to webapp-2275.eu.pythonanywhere.com
- [ ] Configure eu.pythonanywhere.com to accept that subdomain on the current site
- [ ] Update all links in emails, sms:es, etc (move to settings.py or detect somehow)

**Describe alternatives you've considered**
Keep running as is, will confuse people, but it works so this is not critical.

**Additional context**
https://aktivitet.team13.se seems workable.

**Comment by marcus-sonestedt** [comment]
Moving to backlog while we wait for our main website host to set up subdomains. 
(Not likely to happen this year, by the looks of things...)
